In [1]:
%matplotlib notebook
import pandas as pd

In [2]:
data = pd.read_csv('flowdata.csv',index_col = 0,parse_dates = True)
data.head()

                      L06_347  LS06_347  LS06_348
Time
2009-01-01 00:00:00  0.137417  0.097500  0.016833
2009-01-01 03:00:00  0.131250  0.088833  0.016417
2009-01-01 06:00:00  0.113500  0.091250  0.016750
2009-01-01 09:00:00  0.135750  0.091500  0.016250
2009-01-01 12:00:00  0.140917  0.096167  0.017000

### 按时间切片取数据源

In [3]:
data[pd.Timestamp('2012-01-01 09:00'):pd.Timestamp('2012-01-01 19:00')]

                      L06_347  LS06_347  LS06_348
Time
2012-01-01 09:00:00  0.330750  0.293583  0.029750
2012-01-01 12:00:00  0.295000  0.285167  0.031750
2012-01-01 15:00:00  0.301417  0.287750  0.031417
2012-01-01 18:00:00  0.322083  0.304167  0.038083

In [4]:
data[('2012-01-01 09:00'):('2012-01-01 19:00')] #直接取也是可以的

                      L06_347  LS06_347  LS06_348
Time
2012-01-01 09:00:00  0.330750  0.293583  0.029750
2012-01-01 12:00:00  0.295000  0.285167  0.031750
2012-01-01 15:00:00  0.301417  0.287750  0.031417
2012-01-01 18:00:00  0.322083  0.304167  0.038083

### 取最后10个数据

In [5]:
data.tail(10)

                      L06_347  LS06_347  LS06_348
Time
2012-12-31 21:00:00  0.846500  0.846500  0.170167
2013-01-01 00:00:00  1.688333  1.688333  0.207333
2013-01-01 03:00:00  2.693333  2.693333  0.201500
2013-01-01 06:00:00  2.220833  2.220833  0.166917
2013-01-01 09:00:00  2.055000  2.055000  0.175667
2013-01-01 12:00:00  1.710000  1.710000  0.129583
2013-01-01 15:00:00  1.420000  1.420000  0.096333
2013-01-01 18:00:00  1.178583  1.178583  0.083083
2013-01-01 21:00:00  0.898250  0.898250  0.077167
2013-01-02 00:00:00  0.860000  0.860000  0.075000

### 取2013年的数据

In [6]:
data['2013']

                      L06_347  LS06_347  LS06_348
Time
2013-01-01 00:00:00  1.688333  1.688333  0.207333
2013-01-01 03:00:00  2.693333  2.693333  0.201500
2013-01-01 06:00:00  2.220833  2.220833  0.166917
2013-01-01 09:00:00  2.055000  2.055000  0.175667
2013-01-01 12:00:00  1.710000  1.710000  0.129583
2013-01-01 15:00:00  1.420000  1.420000  0.096333
2013-01-01 18:00:00  1.178583  1.178583  0.083083
2013-01-01 21:00:00  0.898250  0.898250  0.077167
2013-01-02 00:00:00  0.860000  0.860000  0.075000

### 按月份区间取

In [7]:
data['2012-01':'2012-03']

                      L06_347  LS06_347  LS06_348
Time
2012-01-01 00:00:00  0.307167  0.273917  0.028000
2012-01-01 03:00:00  0.302917  0.270833  0.030583
2012-01-01 06:00:00  0.331500  0.284750  0.030917
2012-01-01 09:00:00  0.330750  0.293583  0.029750
2012-01-01 12:00:00  0.295000  0.285167  0.031750
...                       ...       ...       ...
2012-03-31 09:00:00  0.104917  0.125000  0.012417
2012-03-31 12:00:00  0.098333  0.124417  0.011833
2012-03-31 15:00:00  0.091917  0.123917  0.011500
2012-03-31 18:00:00  0.085750  0.121417  0.011000
2012-03-31 21:00:00  0.068417  0.119750  0.010417

[728 rows x 3 columns]

### 用bool类型索引判断 取出所有一月份的

In [8]:
data[data.index.month == 1]

                      L06_347  LS06_347  LS06_348
Time
2009-01-01 00:00:00  0.137417  0.097500  0.016833
2009-01-01 03:00:00  0.131250  0.088833  0.016417
2009-01-01 06:00:00  0.113500  0.091250  0.016750
2009-01-01 09:00:00  0.135750  0.091500  0.016250
2009-01-01 12:00:00  0.140917  0.096167  0.017000
...                       ...       ...       ...
2013-01-01 12:00:00  1.710000  1.710000  0.129583
2013-01-01 15:00:00  1.420000  1.420000  0.096333
2013-01-01 18:00:00  1.178583  1.178583  0.083083
2013-01-01 21:00:00  0.898250  0.898250  0.077167
2013-01-02 00:00:00  0.860000  0.860000  0.075000

[1001 rows x 3 columns]

### 用bool类型索引判断 取出8点到12点的

In [9]:
data[(data.index.hour > 8) & (data.index.hour <12)]

                      L06_347  LS06_347  LS06_348
Time
2009-01-01 09:00:00  0.135750  0.091500  0.016250
2009-01-02 09:00:00  0.141917  0.097083  0.016417
2009-01-03 09:00:00  0.124583  0.084417  0.015833
2009-01-04 09:00:00  0.109000  0.105167  0.018000
2009-01-05 09:00:00  0.161500  0.114583  0.021583
...                       ...       ...       ...
2012-12-28 09:00:00  0.961500  0.961500  0.092417
2012-12-29 09:00:00  0.786833  0.786833  0.077000
2012-12-30 09:00:00  0.916000  0.916000  0.101583
2012-12-31 09:00:00  0.682750  0.682750  0.066583
2013-01-01 09:00:00  2.055000  2.055000  0.175667

[1462 rows x 3 columns]

In [10]:
data.between_time('08:00','12:00') # 也可以这样取

                      L06_347  LS06_347  LS06_348
Time
2009-01-01 09:00:00  0.135750  0.091500  0.016250
2009-01-01 12:00:00  0.140917  0.096167  0.017000
2009-01-02 09:00:00  0.141917  0.097083  0.016417
2009-01-02 12:00:00  0.147833  0.101917  0.016417
2009-01-03 09:00:00  0.124583  0.084417  0.015833
...                       ...       ...       ...
2012-12-30 12:00:00  1.465000  1.465000  0.086833
2012-12-31 09:00:00  0.682750  0.682750  0.066583
2012-12-31 12:00:00  0.651250  0.651250  0.063833
2013-01-01 09:00:00  2.055000  2.055000  0.175667
2013-01-01 12:00:00  1.710000  1.710000  0.129583

[2924 rows x 3 columns]

### 时间序列的重采样

In [11]:
data.head()

                      L06_347  LS06_347  LS06_348
Time
2009-01-01 00:00:00  0.137417  0.097500  0.016833
2009-01-01 03:00:00  0.131250  0.088833  0.016417
2009-01-01 06:00:00  0.113500  0.091250  0.016750
2009-01-01 09:00:00  0.135750  0.091500  0.016250
2009-01-01 12:00:00  0.140917  0.096167  0.017000

In [12]:
# 以天为单位计算（重采样）平均值
data.resample('D').mean().head()

             L06_347  LS06_347  LS06_348
Time
2009-01-01  0.125010  0.092281  0.016635
2009-01-02  0.124146  0.095781  0.016406
2009-01-03  0.113562  0.085542  0.016094
2009-01-04  0.140198  0.102708  0.017323
2009-01-05  0.128812  0.104490  0.018167

In [13]:
# 以天为单位计算（重采样）最大值
data.resample('D').max().head()

             L06_347  LS06_347  LS06_348
Time
2009-01-01  0.140917  0.097500  0.017583
2009-01-02  0.147833  0.101917  0.016833
2009-01-03  0.135833  0.092500  0.016833
2009-01-04  0.160417  0.113750  0.018417
2009-01-05  0.161500  0.115167  0.021583

In [14]:
# 以3天为单位重采样 平均值
data.resample('3D').mean().head()

             L06_347  LS06_347  LS06_348
Time
2009-01-01  0.120906  0.091201  0.016378
2009-01-04  0.121594  0.091708  0.016670
2009-01-07  0.097042  0.070740  0.014479
2009-01-10  0.115941  0.086340  0.014545
2009-01-13  0.346962  0.364549  0.034198

In [15]:
# 以月为单位
data.resample('M').mean().head()

             L06_347  LS06_347  LS06_348
Time
2009-01-31  0.517864  0.536660  0.045597
2009-02-28  0.516847  0.529987  0.047238
2009-03-31  0.373157  0.383172  0.037508
2009-04-30  0.163182  0.129354  0.021356
2009-05-31  0.178588  0.160616  0.020744

In [16]:
# 画一个图，注意看开头的魔法指令
data.resample('M').mean().plot()